# Use a Python base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the project files into the container
COPY . /app

# Install any necessary dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Make the bash file executable
RUN chmod +x pipeline.sh

# Set the entrypoint to run the bash file
ENTRYPOINT ["./pipeline.sh"]
